"use client";

import { AnimatePresence, motion } from "framer-motion";
import { CheckCircle2, Github, History, Mic, Play, Settings2, Sparkles, Volume2, Waves } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { currentContext } from "@/lib/founder-memory";
import { createBrowserSpeechToText, createBrowserTextToSpeech, type SpeechStatus } from "@/lib/voice/speech";
import { cn } from "@/lib/utils";

const phases: { id: SpeechStatus; label: string }[] = [{ id: "listening", label: "Listening" }, { id: "understanding", label: "Understanding" }, { id: "searching", label: "Searching Timeline" }, { id: "searching", label: "Checking GitHub" }, { id: "searching", label: "Reviewing Decisions" }, { id: "collaborating", label: "Collaborating" }];
const perspectives = [
  ["Nova", "Product strategy", "Launch the onboarding cohort this week. The customer evidence is direct and the smallest release gives you the fastest learning loop."],
  ["Atlas", "Engineering", "Authentication verification is the single engineering gate. Complete it before launch; do not widen the scope."],
  ["Echo", "Founder memory", "Testing was postponed twice before recent launches. Naming and completing it today breaks that pattern."],
  ["Pulse", "Market signals", "Customer feedback points to first-session confidence as the meaningful differentiator."],
  ["Compass", "Long-term vision", "A narrow, measured release builds the decision muscle needed for a durable founder operating system."],
] as const;
const commands = ["Create a project", "Log a decision", "Open timeline", "Search GitHub", "Summarize this week", "What am I working on?", "What should I do next?", "Find onboarding decisions"];

export function VoiceWorkspace() {
  const [wakePhrase, setWakePhrase] = useState("Hey Nova");
  const [editingWakePhrase, setEditingWakePhrase] = useState(false);
  const [transcript, setTranscript] = useState("Should I launch onboarding this week?");
  const [status, setStatus] = useState<SpeechStatus>("idle");
  const [step, setStep] = useState(-1);
  const [speak, setSpeak] = useState(false);
  const stt = useMemo(() => createBrowserSpeechToText(), []);
  const tts = useMemo(() => createBrowserTextToSpeech(), []);
  const running = status !== "idle" && status !== "complete";
  const begin = () => { setStep(0); setStatus("listening"); };
  useEffect(() => { if (step < 0 || step >= phases.length) return; const timer = window.setTimeout(() => { const next = step + 1; if (next === phases.length) { setStatus("complete"); setStep(next); if (speak && tts.supported) tts.speak("Launch the onboarding cohort this week after authentication testing is complete."); } else { setStep(next); setStatus(phases[next].id); } }, step === 0 ? 900 : 850); return () => window.clearTimeout(timer); }, [step, speak, tts]);
  const startMicrophone = () => { if (stt.supported) { stt.start((text) => setTranscript(text)); } begin(); };
  const command = (value: string) => { setTranscript(value); begin(); };
  return <div className="mx-auto w-full max-w-7xl px-5 py-9 sm:px-8 lg:px-10 lg:py-12">
    <section className="animate-rise border-b border-border/70 pb-9"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-primary">Voice Workspace</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.035em] sm:text-5xl">Think out loud.<br />Keep the whole company in mind.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-muted-foreground">Voice is a calm command surface for your project, timeline, repository, decisions, and founder history—not another chat window.</p></div><div className="flex items-center gap-3"><button onClick={() => setEditingWakePhrase(!editingWakePhrase)} className="rounded-lg border border-border bg-card px-3 py-2 text-sm text-muted-foreground transition-colors hover:border-primary/40 hover:text-foreground"><Settings2 className="mr-2 inline size-4 text-primary" />{wakePhrase}</button><span className="flex items-center gap-2 text-xs text-muted-foreground"><span className="size-1.5 rounded-full bg-primary" />Context is live</span></div></div></section>
    {editingWakePhrase && <motion.section initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} className="mt-5 overflow-hidden rounded-xl border border-primary/25 bg-primary/[0.06] p-4"><label className="text-sm font-medium">Wake phrase <input value={wakePhrase} onChange={(event) => setWakePhrase(event.target.value)} className="ml-3 rounded border border-border bg-background px-3 py-1.5 text-sm outline-none focus:ring-2 focus:ring-ring" /></label><p className="mt-2 text-xs text-muted-foreground">Use Nova, Atlas, Echo, or a phrase that feels natural to your working rhythm.</p></motion.section>}
    <div className="mt-8 grid gap-8 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,0.85fr)]"><div className="space-y-8"><section className="animate-rise animation-delay-1 overflow-hidden rounded-xl border border-primary/25 bg-gradient-to-br from-primary/[0.12] via-card to-card p-6 sm:p-8" aria-labelledby="voice-title"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Live voice session</p><h2 id="voice-title" className="mt-2 text-xl font-semibold tracking-tight">{status === "idle" ? "Ready when you are." : status === "complete" ? "Shared recommendation ready." : phases[Math.min(step, phases.length - 1)].label + "…"}</h2></div><button onClick={() => setSpeak(!speak)} className={cn("flex size-10 items-center justify-center rounded-lg border transition-colors", speak ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card text-muted-foreground")} aria-pressed={speak} aria-label="Toggle spoken recommendations"><Volume2 className="size-4" /></button></div><div className="mt-8 flex min-h-36 items-center justify-center"><motion.button onClick={startMicrophone} whileTap={{ scale: 0.96 }} className="group relative flex size-28 items-center justify-center rounded-full border border-primary/40 bg-primary/[0.1] text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" aria-label="Start voice input"><AnimatePresence>{running && <motion.span initial={{ opacity: 0, scale: 0.6 }} animate={{ opacity: 1, scale: [1, 1.35, 1] }} transition={{ repeat: Infinity, duration: 1.6 }} className="absolute inset-[-14px] rounded-full border border-primary/30" />}</AnimatePresence><Waves className={cn("size-9 transition-transform", running && "animate-pulse")} /></motion.button></div><div className="mx-auto max-w-2xl text-center"><textarea value={transcript} onChange={(event) => setTranscript(event.target.value)} rows={2} className="w-full resize-none bg-transparent text-center text-xl font-medium tracking-tight outline-none placeholder:text-muted-foreground sm:text-2xl" aria-label="Voice transcript" /><p className="mt-3 text-sm text-muted-foreground">{stt.supported ? "Tap the waveform to speak, or refine the live transcript." : "Voice transcription is unavailable in this browser—type or use a supported browser."}</p></div><div className="mt-7 flex flex-col gap-3 border-t border-primary/15 pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-muted-foreground">Project: <span className="text-foreground">{currentContext.project}</span> · Repo: <span className="text-foreground">{currentContext.repository}</span></p><Button onClick={begin} disabled={!transcript.trim() || running}>{running ? "Working across the room" : "Run voice briefing"}<Play className="ml-2 size-4" /></Button></div></section>
    <section className="animate-rise animation-delay-2" aria-labelledby="flow-title"><Header eyebrow="Voice flow" title="Context appears before the answer." id="flow-title" /><div className="mt-5 grid gap-2 sm:grid-cols-3">{phases.map((phase, index) => <motion.div key={`${phase.label}-${index}`} animate={{ opacity: step >= index ? 1 : 0.42, y: step >= index ? 0 : 4 }} className={cn("rounded-lg border p-3 text-sm", step === index ? "border-primary/50 bg-primary/[0.08]" : "border-border bg-card/55")}><span className="flex items-center gap-2"><span className={cn("size-1.5 rounded-full", step >= index ? "bg-primary" : "bg-muted-foreground")} />{phase.label}</span></motion.div>)}</div></section>
    {status === "complete" && <motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="rounded-xl border border-primary/25 bg-card/65 p-6" aria-labelledby="consensus-title"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-primary"><Sparkles className="size-4" />Shared recommendation</p><h2 id="consensus-title" className="mt-3 text-2xl font-semibold tracking-tight">Launch this week—after testing auth today.</h2><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">The room agrees that onboarding should ship to a small founder cohort, with authentication verification as the one non-negotiable gate.</p><div className="mt-6 flex items-center justify-between rounded-lg border border-border bg-background/45 p-4"><span className="text-sm">Decision and reasoning added to your timeline.</span><span className="flex items-center gap-2 text-sm text-emerald-300"><CheckCircle2 className="size-4" />86% confidence</span></div></motion.section>}</div>
    <aside className="space-y-8"><section className="animate-rise animation-delay-2" aria-labelledby="agents-title"><Header eyebrow="Multi-agent voice" title="Independent thought, one voice." id="agents-title" /><div className="mt-5 space-y-3">{perspectives.map(([name, role, thought], index) => <motion.article key={name} initial={false} animate={{ opacity: step >= index + 1 || status === "complete" ? 1 : 0.46, y: step >= index + 1 || status === "complete" ? 0 : 5 }} className="rounded-lg border border-border bg-card/55 p-4"><div className="flex justify-between"><div><p className="text-sm font-medium">{name}</p><p className="text-xs text-muted-foreground">{role}</p></div>{step === index + 1 && <span className="flex gap-1 pt-1"><i className="size-1.5 animate-pulse rounded-full bg-primary" /><i className="size-1.5 animate-pulse rounded-full bg-primary [animation-delay:150ms]" /></span>}</div><p className="mt-3 text-sm leading-6 text-muted-foreground">{step >= index + 1 || status === "complete" ? thought : `${name} will join when this question needs their perspective.`}</p></motion.article>)}</div></section><section className="animate-rise animation-delay-3 rounded-xl border border-border bg-card/55 p-5"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Voice commands</p><div className="mt-4 flex flex-wrap gap-2">{commands.map((item) => <button key={item} onClick={() => command(item)} className="rounded-full border border-border px-3 py-1.5 text-xs text-muted-foreground transition-colors hover:border-primary/40 hover:text-foreground">{item}</button>)}</div></section></aside></div>
    <section className="mt-10 flex flex-wrap gap-x-6 gap-y-3 border-t border-border/70 pt-6 text-xs text-muted-foreground"><span><kbd className="mr-2 rounded border border-border bg-card px-1.5 py-1 font-sans text-[10px] text-foreground">Ctrl ⇧ V</kbd>Start Voice Workspace</span><span><Mic className="mr-1 inline size-3.5 text-primary" />Wake phrase: {wakePhrase}</span><span><Github className="mr-1 inline size-3.5 text-primary" />Repository-aware</span><span><History className="mr-1 inline size-3.5 text-primary" />Timeline-aware</span></section>
  </div>;
}
function Header({ eyebrow, title, id }: { eyebrow: string; title: string; id: string }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">{eyebrow}</p><h2 id={id} className="mt-2 text-xl font-semibold tracking-tight">{title}</h2></div>; }
