"use client";

import { motion } from "framer-motion";
import { BarChart3, BookOpenCheck, BrainCircuit, ChevronRight, CircleDot, GitCommitHorizontal, Lightbulb, Link2, Rocket, Users } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { intelligentNotifications, onboardingReplay, weeklyIntelligence } from "@/lib/founder-memory";
import { cn } from "@/lib/utils";

const iconByKind: Record<string, LucideIcon> = { idea: Lightbulb, feedback: Users, prototype: BrainCircuit, commit: GitCommitHorizontal, launch: Rocket, metric: BarChart3, lesson: BookOpenCheck, decision: CircleDot };
const dna = [["Decision speed", "More deliberate, fewer reversals", 76], ["Execution consistency", "Strong three-week rhythm", 84], ["Learning velocity", "Compounding from customer signals", 89], ["Risk appetite", "Measured at launch", 64], ["Focus score", "Protected around one outcome", 78], ["Communication style", "Clearer in product decisions", 73], ["Shipping momentum", "Rising", 86]] as const;
const graph = [["Project", "Logfound activation", "18%", "46%"], ["Feature", "Onboarding", "38%", "22%"], ["Commit", "e1e13f4", "56%", "50%"], ["Feedback", "First-session clarity", "71%", "23%"], ["Launch", "10-founder cohort", "82%", "60%"], ["Lesson", "Test before launch", "51%", "77%"]] as const;

export function FounderReplay() {
  const [selected, setSelected] = useState(onboardingReplay.events[0]);
  const [graphNode, setGraphNode] = useState<(typeof graph)[number]>(graph[0]);
  return <div className="mx-auto w-full max-w-7xl px-5 py-9 sm:px-8 lg:px-10 lg:py-12">
    <section className="animate-rise border-b border-border/70 pb-9"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-primary">Founder Replay</p><div className="mt-3 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-4xl font-semibold tracking-[-0.035em] sm:text-5xl">Replay the decisions<br />that built the company.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-muted-foreground">Every idea, customer signal, commit, launch, and learning remains connected—so context compounds instead of disappearing.</p></div><Button variant="outline" onClick={() => document.getElementById("weekly-review")?.scrollIntoView({ behavior: "smooth" })}>Open weekly review <ChevronRight className="ml-2 size-4" /></Button></div></section>
    <div className="mt-8 grid gap-8 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,0.85fr)]"><div className="space-y-8"><section className="animate-rise animation-delay-1" aria-labelledby="replay-title"><Heading eyebrow="Replay timeline" id="replay-title" title={onboardingReplay.title} /><div className="mt-5 rounded-xl border border-border bg-card/45 px-5 py-2 sm:px-7">{onboardingReplay.events.map((event, index) => <ReplayEvent key={event.id} event={event} active={selected.id === event.id} onSelect={() => setSelected(event)} last={index === onboardingReplay.events.length - 1} />)}</div></section><section className="animate-rise animation-delay-2 rounded-xl border border-primary/25 bg-gradient-to-br from-primary/[0.1] via-card to-card p-6 sm:p-7" aria-labelledby="decision-title"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Immersive replay</p><h2 id="decision-title" className="mt-3 text-2xl font-semibold tracking-tight">{selected.title}</h2><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">{selected.detail}</p><div className="mt-7 grid gap-5 border-t border-primary/15 pt-6 sm:grid-cols-2"><ReplayDetail label="Original problem" value={onboardingReplay.problem} /><ReplayDetail label="AI reasoning" value="Nova saw an activation opportunity; Atlas named authentication testing as the only engineering gate; Echo found the repeated testing delay." /><ReplayDetail label="GitHub connection" value="e1e13f4 established the workspace surface where onboarding now begins." /><ReplayDetail label="Final decision" value={onboardingReplay.decision} /><ReplayDetail label="Outcome" value={onboardingReplay.outcome} /><ReplayDetail label="Lesson learned" value={onboardingReplay.lesson} /></div></section></div>
    <aside className="space-y-8"><section className="animate-rise animation-delay-2 rounded-xl border border-border bg-card/55 p-5" aria-labelledby="notifications-title"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Intelligent notifications</p><h2 id="notifications-title" className="mt-2 text-xl font-semibold tracking-tight">Signals worth interrupting for.</h2><div className="mt-5 space-y-3">{intelligentNotifications.map((notice) => <article key={notice.title} className={cn("rounded-lg border p-4", notice.tone === "amber" ? "border-amber-300/20 bg-amber-300/[0.04]" : notice.tone === "violet" ? "border-violet-400/20 bg-violet-400/[0.04]" : "border-primary/20 bg-primary/[0.05]")}><p className="text-sm font-medium">{notice.title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{notice.detail}</p><p className="mt-3 text-xs text-primary">Observed by {notice.agent}</p></article>)}</div></section><FounderDna /></aside></div>
    <section className="mt-10 animate-rise animation-delay-3" aria-labelledby="graph-title"><Heading eyebrow="Decision graph" id="graph-title" title="Relationships, not folders." /><div className="relative mt-5 min-h-[360px] overflow-hidden rounded-xl border border-border bg-card/45 p-5"><svg className="absolute inset-0 size-full text-border" aria-hidden="true" viewBox="0 0 1000 360" preserveAspectRatio="none"><path d="M160 166 L385 80 L555 180 L710 82 L825 220 M385 80 L510 278 M510 278 L825 220" fill="none" stroke="currentColor" strokeWidth="1.25" strokeDasharray="5 5" /></svg>{graph.map((node) => <motion.button key={node[1]} initial={{ opacity: 0, scale: 0.75 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: 0.1 }} onClick={() => setGraphNode(node)} style={{ left: node[2], top: node[3] }} className={cn("absolute -translate-x-1/2 -translate-y-1/2 rounded-full border px-3 py-2 text-xs font-medium shadow-lg transition-all hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring", graphNode[1] === node[1] ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card text-foreground hover:border-primary/50")}>{node[0]} · {node[1]}</motion.button>)}<div className="absolute bottom-5 left-5 right-5 rounded-lg border border-border bg-background/80 p-4 backdrop-blur-sm"><p className="flex items-center gap-2 text-sm font-medium"><Link2 className="size-4 text-primary" />{graphNode[0]} · {graphNode[1]}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">This node is connected to the onboarding decision, the first-session customer signal, and the release learning loop.</p></div></div></section>
    <section id="weekly-review" className="mt-10 grid gap-8 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,0.85fr)]"><section className="animate-rise animation-delay-3" aria-labelledby="weekly-title"><Heading eyebrow="Weekly intelligence" id="weekly-title" title="The week, turned into learning." /><div className="mt-5 grid gap-3 sm:grid-cols-2">{weeklyIntelligence.map(([title, detail]) => <article key={title} className="rounded-xl border border-border bg-card/55 p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">{title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{detail}</p></article>)}</div></section><section className="animate-rise animation-delay-3 rounded-xl border border-border bg-card/55 p-5" aria-labelledby="summary-title"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Weekly review</p><h2 id="summary-title" className="mt-2 text-xl font-semibold tracking-tight">Your strongest move was protecting scope.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">You turned an ambiguous activation problem into a measured launch path, with more customer evidence and fewer unplanned branches than the prior week.</p><div className="mt-6 border-t border-border pt-5"><p className="text-sm font-medium">Next week’s invitation</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Keep the customer interview habit. Complete authentication validation before the next feature expands the surface.</p></div></section></section>
    <section className="mt-10 flex flex-wrap gap-x-6 gap-y-3 border-t border-border/70 pt-6 text-xs text-muted-foreground"><span><kbd className="mr-2 rounded border border-border bg-card px-1.5 py-1 font-sans text-[10px] text-foreground">Ctrl ⇧ P</kbd>Replay decision</span><span><kbd className="mr-2 rounded border border-border bg-card px-1.5 py-1 font-sans text-[10px] text-foreground">Ctrl ⇧ W</kbd>Weekly review</span><span><kbd className="mr-2 rounded border border-border bg-card px-1.5 py-1 font-sans text-[10px] text-foreground">Ctrl ⇧ D</kbd>Founder DNA</span></section>
  </div>;
}
function Heading({ eyebrow, id, title }: { eyebrow: string; id: string; title: string }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">{eyebrow}</p><h2 id={id} className="mt-2 text-xl font-semibold tracking-tight sm:text-2xl">{title}</h2></div>; }
function ReplayEvent({ event, active, onSelect, last }: { event: (typeof onboardingReplay.events)[number]; active: boolean; onSelect: () => void; last: boolean }) { const Icon = iconByKind[event.kind]; return <button onClick={onSelect} className="relative grid w-full grid-cols-[30px_1fr] gap-3 py-5 text-left"><div className="relative flex justify-center"><span className={cn("z-10 flex size-7 items-center justify-center rounded-full border", active ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card text-primary")}><Icon className="size-3.5" /></span>{!last && <span className="absolute top-7 h-[calc(100%+12px)] w-px bg-border" />}</div><div className={cn("rounded-lg p-2 transition-colors", active && "bg-primary/[0.06]")}><div className="flex flex-col gap-1 sm:flex-row sm:justify-between"><h3 className="text-sm font-medium">{event.title}</h3><time className="text-xs text-muted-foreground">{event.date}</time></div><p className="mt-1 text-sm leading-6 text-muted-foreground">{event.detail}</p><p className="mt-2 text-xs text-primary">{event.source}</p></div></button>; }
function ReplayDetail({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">{label}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{value}</p></div>; }
function FounderDna() { return <section id="founder-dna" className="animate-rise animation-delay-3" aria-labelledby="dna-title"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Founder DNA</p><h2 id="dna-title" className="mt-2 text-xl font-semibold tracking-tight">A profile in motion.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">A living read on how you build—not a generic analytics scorecard.</p><div className="mt-5 space-y-4">{dna.map(([name, descriptor, value]) => <div key={name}><div className="flex justify-between gap-3 text-sm"><span>{name}</span><span className="text-right text-muted-foreground">{descriptor}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-secondary"><motion.div initial={{ width: 0 }} whileInView={{ width: `${value}%` }} viewport={{ once: true }} className="h-full rounded-full bg-primary/80" /></div></div>)}</div><div className="mt-6 rounded-lg border border-primary/20 bg-primary/[0.07] p-4"><p className="text-sm font-medium">Strength</p><p className="mt-1 text-sm leading-6 text-muted-foreground">You turn customer evidence into a focused shipping plan.</p><p className="mt-4 text-sm font-medium">Growth area</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Move validation earlier, while the decision is still small.</p></div></section>; }
