"use client";

import { Activity, AlertTriangle, BarChart3, BookOpenCheck, Bot, CheckCircle2, ChevronRight, Code2, Github, GitCommitHorizontal, Lock, Search, ShieldCheck, Sparkles, Star, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { GithubLiveActivity } from "@/components/github/github-live-activity";
import { useKeyboardShortcuts } from "@/hooks/use-keyboard-shortcuts";
import { cn } from "@/lib/utils";

const repositories = [
  { name: "logfound-web", description: "Founder operating system", language: "TypeScript", visibility: "Private", updated: "8 min ago", branches: 4, stars: null, contributors: ["S", "M", "A"] },
  { name: "logfound-api", description: "Product API and worker services", language: "TypeScript", visibility: "Private", updated: "Yesterday", branches: 2, stars: null, contributors: ["S", "A"] },
  { name: "signal-kit", description: "Open-source decision utilities", language: "TypeScript", visibility: "Public", updated: "Jun 28", branches: 3, stars: 124, contributors: ["S", "K", "P"] },
];
const commits = [
  { hash: "e1e13f4", title: "Build founder dashboard workspace", summary: "Added the founder dashboard, focused daily work surface, and keyboard-first actions.", impact: "Completes roughly 60% of the activation flow.", risk: "Dashboard actions need persistence before a broad release.", time: "Today · 10:42", tone: "text-primary" },
  { hash: "ebb3f16", title: "Build founder intelligence engine", summary: "Introduced the multi-agent strategy room, memory, and decision graph.", impact: "Creates a distinct reason for founders to return after the first session.", risk: "Decision memory needs real repository events to stay current.", time: "Today · 09:18", tone: "text-violet-300" },
  { hash: "b5ac90d", title: "feat: add Supabase auth boundary", summary: "Established typed browser and server clients around authentication state.", impact: "Unblocks protected workspace experiences.", risk: "No end-to-end validation covers the complete sign-in path yet.", time: "Yesterday · 16:06", tone: "text-emerald-300" },
];
const health = [
  ["Deployment ready", "The current main branch builds successfully and has a clean production path.", CheckCircle2, "text-emerald-300"],
  ["Test coverage", "Auth and activation paths need coverage before the next broad launch.", Activity, "text-amber-200"],
  ["Documentation", "Architecture notes are clear; add an onboarding flow decision record.", BookOpenCheck, "text-primary"],
  ["Security", "Supabase keys are environment-bound and server cookies are isolated.", ShieldCheck, "text-emerald-300"],
  ["Code quality", "Typed boundaries and shared UI primitives are keeping the surface coherent.", Code2, "text-primary"],
  ["Technical debt", "Authentication appears in four places; consolidate before payments.", AlertTriangle, "text-amber-200"],
] as const;

export function GithubIntelligence() {
  const [picker, setPicker] = useState(false);
  const [repo, setRepo] = useState(repositories[0]);
  const [query, setQuery] = useState("What changed last week?");
  const [asked, setAsked] = useState(true);
  const openPicker = () => setPicker(true);
  useKeyboardShortcuts([{ key: "g", meta: true, shift: true, handler: openPicker }, { key: "r", meta: true, shift: true, handler: openPicker }, { key: "c", meta: true, shift: true, handler: () => document.getElementById("commit-history")?.scrollIntoView({ behavior: "smooth" }) }]);
  return <div className="mx-auto w-full max-w-7xl px-5 py-9 sm:px-8 lg:px-10 lg:py-12">
    <section className="animate-rise border-b border-border/70 pb-9"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-primary">GitHub Intelligence</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.035em] sm:text-5xl">Your codebase, understood.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-muted-foreground">Logfound translates repository movement into product context, engineering memory, and the decisions that should come next.</p></div><div className="flex gap-2"><Button variant="outline" onClick={openPicker}>Browse demo repositories</Button><a href="/settings" className="inline-flex h-10 items-center justify-center rounded-md px-4 text-sm font-medium text-muted-foreground transition-colors hover:bg-accent hover:text-foreground">Connection settings</a></div></div></section>
    <GithubLiveActivity />
    <section className="mt-8 animate-rise animation-delay-1 rounded-xl border border-border bg-card/55 p-5 sm:p-6" aria-labelledby="repo-title"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><span className="flex size-11 items-center justify-center rounded-lg border border-primary/25 bg-primary/[0.1] text-primary"><Github className="size-5" /></span><div><div className="flex items-center gap-2"><h2 id="repo-title" className="text-lg font-semibold">{repo.name}</h2><span className="rounded border border-border px-1.5 py-0.5 text-[10px] uppercase tracking-wide text-muted-foreground">{repo.visibility}</span></div><p className="mt-1 text-sm text-muted-foreground">{repo.description} · demo context</p></div></div><div className="grid grid-cols-3 divide-x divide-border text-sm"><RepoMetric label="Language" value={repo.language} /><RepoMetric label="Branches" value={String(repo.branches)} /><RepoMetric label={repo.stars ? "Stars" : "Contributors"} value={repo.stars ? String(repo.stars) : String(repo.contributors.length)} /></div></div><div className="mt-5 flex items-center gap-2 border-t border-border pt-4"><span className="text-xs text-muted-foreground">Recent contributors</span><div className="flex -space-x-2">{repo.contributors.map((initial, index) => <span key={`${initial}-${index}`} className="flex size-6 items-center justify-center rounded-full border border-card bg-secondary text-[10px] font-medium">{initial}</span>)}</div><span className="ml-auto flex items-center gap-1 text-xs text-muted-foreground"><span className="size-1.5 rounded-full bg-muted-foreground" />Demo data</span></div></section>
    <div className="mt-8 grid gap-8 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,0.82fr)]"><div className="space-y-8"><section className="animate-rise animation-delay-2" id="commit-history" aria-labelledby="timeline-title"><SectionTitle eyebrow="AI code timeline" id="timeline-title" title="Every commit, with the why attached." /><div className="mt-5 rounded-xl border border-border bg-card/45 px-5 py-2 sm:px-7">{commits.map((commit, index) => <CommitCard key={commit.hash} commit={commit} last={index === commits.length - 1} />)}</div></section><section className="animate-rise animation-delay-3" aria-labelledby="report-title"><SectionTitle eyebrow="Weekly engineering report" id="report-title" title="The engineering story this week." /><div className="mt-5 grid gap-3 sm:grid-cols-3"><ReportMetric value="42" label="commits" /><ReportMetric value="06" label="features completed" /><ReportMetric value="03" label="bugs fixed" /></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><ReportNote title="Meaningful movement" text="Authentication finished · API latency improved · Timeline became the largest feature." /><ReportNote title="Working rhythm" text="Tuesday was your most productive day. /app/dashboard was the most modified folder." /></div></section></div>
    <aside className="space-y-8"><section className="animate-rise animation-delay-2 rounded-xl border border-primary/25 bg-gradient-to-br from-primary/[0.12] via-card to-card p-5" aria-labelledby="memory-title"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Engineering memory</p><h2 id="memory-title" className="mt-2 text-xl font-semibold tracking-tight">Ask the codebase.</h2><div className="mt-5 rounded-lg border border-border bg-background/60 p-3"><label className="flex items-center gap-2"><Search className="size-4 text-muted-foreground" /><span className="sr-only">Search engineering memory</span><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") setAsked(true); }} className="w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground" /></label></div><Button className="mt-3 w-full" variant="secondary" onClick={() => setAsked(true)}>Search repository memory <ChevronRight className="ml-2 size-4" /></Button>{asked && <div className="mt-5 border-l border-primary/60 pl-4"><p className="text-sm font-medium">A week of product surface area.</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Dashboard and Intelligence became the main product work. Authentication boundaries landed, while full sign-in validation remains the clearest release risk.</p><p className="mt-3 text-xs text-primary">References: e1e13f4 · ebb3f16 · b5ac90d</p></div>}</section><ContextAgents /></aside></div>
    <section className="mt-10 animate-rise animation-delay-3" aria-labelledby="health-title"><SectionTitle eyebrow="Repository health" id="health-title" title="A quiet read on the system." /><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{health.map(([title, observation, Icon, tone]) => <article key={title} className="rounded-xl border border-border bg-card/55 p-5 transition-all duration-300 hover:-translate-y-0.5 hover:border-primary/30"><div className="flex items-center justify-between"><h3 className="font-medium">{title}</h3><Icon className={cn("size-4", tone)} /></div><p className="mt-5 text-sm leading-6 text-muted-foreground">{observation}</p></article>)}</div></section>
    <section className="mt-10 flex flex-wrap gap-x-6 gap-y-3 border-t border-border/70 pt-6 text-xs text-muted-foreground" aria-label="GitHub keyboard shortcuts"><span><kbd className="mr-2 rounded border border-border bg-card px-1.5 py-1 font-sans text-[10px] text-foreground">Ctrl ⇧ G</kbd>Open GitHub</span><span><kbd className="mr-2 rounded border border-border bg-card px-1.5 py-1 font-sans text-[10px] text-foreground">Ctrl ⇧ R</kbd>Repository search</span><span><kbd className="mr-2 rounded border border-border bg-card px-1.5 py-1 font-sans text-[10px] text-foreground">Ctrl ⇧ C</kbd>Commit history</span></section>
    {picker && <RepoPicker repositories={repositories} selected={repo.name} onSelect={(next) => { setRepo(next); setPicker(false); }} onClose={() => setPicker(false)} />}
  </div>;
}
function RepoPicker({ repositories: options, selected, onSelect, onClose }: { repositories: typeof repositories; selected: string; onSelect: (repo: typeof repositories[number]) => void; onClose: () => void }) { return <div className="fixed inset-0 z-40 flex items-start justify-center bg-background/80 p-4 pt-[13vh] backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="repo-picker-title" onClick={onClose}><div className="w-full max-w-2xl rounded-xl border border-border bg-card p-5 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Repository connection</p><h2 id="repo-picker-title" className="mt-1 text-xl font-semibold">Select a repository</h2></div><button className="rounded-md p-2 text-muted-foreground hover:bg-accent" onClick={onClose} aria-label="Close repository selection"><X className="size-4" /></button></div><div className="mt-5 space-y-2">{options.map((option) => <button key={option.name} onClick={() => onSelect(option)} className={cn("flex w-full items-center justify-between rounded-lg border p-4 text-left transition-colors", selected === option.name ? "border-primary/50 bg-primary/[0.07]" : "border-border hover:border-primary/30 hover:bg-accent/40")}><div><p className="font-medium">{option.name}</p><p className="mt-1 text-sm text-muted-foreground">{option.description} · {option.language}</p></div><span className="flex items-center gap-2 text-xs text-muted-foreground">{option.visibility === "Private" ? <Lock className="size-3.5" /> : <Star className="size-3.5" />}{option.visibility}</span></button>)}</div></div></div>; }
function RepoMetric({ label, value }: { label: string; value: string }) { return <div className="px-4"><p className="text-[10px] uppercase tracking-[0.15em] text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
function SectionTitle({ eyebrow, id, title }: { eyebrow: string; id: string; title: string }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">{eyebrow}</p><h2 id={id} className="mt-2 text-xl font-semibold tracking-tight sm:text-2xl">{title}</h2></div>; }
function CommitCard({ commit, last }: { commit: typeof commits[number]; last: boolean }) { return <article className="relative grid grid-cols-[30px_1fr] gap-3 py-6"><div className="relative flex justify-center"><span className={cn("z-10 flex size-7 items-center justify-center rounded-full border border-border bg-card", commit.tone)}><GitCommitHorizontal className="size-3.5" /></span>{!last && <span className="absolute top-7 h-[calc(100%+18px)] w-px bg-border" />}</div><div><div className="flex flex-col gap-1 sm:flex-row sm:justify-between"><div><h3 className="text-sm font-medium">GitHub commit · {commit.title}</h3><p className="mt-1 font-mono text-[11px] text-muted-foreground">{commit.hash}</p></div><time className="text-xs text-muted-foreground">{commit.time}</time></div><div className="mt-4 grid gap-3 border-l border-border pl-4 text-sm"><Insight label="AI summary" text={commit.summary} Icon={Sparkles} /><Insight label="Impact" text={commit.impact} Icon={BarChart3} /><Insight label="Potential risk" text={commit.risk} Icon={AlertTriangle} /></div></div></article>; }
function Insight({ label, text, Icon }: { label: string; text: string; Icon: LucideIcon }) { return <div><p className="flex items-center gap-2 text-xs font-medium text-foreground"><Icon className="size-3.5 text-primary" />{label}</p><p className="mt-1 leading-6 text-muted-foreground">{text}</p></div>; }
function ReportMetric({ value, label }: { value: string; label: string }) { return <article className="rounded-xl border border-border bg-card/55 p-5"><p className="text-3xl font-semibold tracking-tight text-primary">{value}</p><p className="mt-1 text-sm text-muted-foreground">{label}</p></article>; }
function ReportNote({ title, text }: { title: string; text: string }) { return <article className="rounded-xl border border-border bg-card/55 p-5"><p className="font-medium">{title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>; }
function ContextAgents() { const notes = [["Atlas", "Authentication is duplicated across four components; refactoring now reduces payment integration risk."], ["Nova", "This refactor protects product velocity before the next feature adds surface area."], ["Echo", "Authentication was delayed twice before launch; resolve it while the context is fresh."]]; return <section className="animate-rise animation-delay-3" aria-labelledby="agents-title"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Context-aware agents</p><h2 id="agents-title" className="mt-2 text-xl font-semibold tracking-tight">The repository is in the room.</h2><div className="mt-5 space-y-3">{notes.map(([name, note]) => <article key={name} className="rounded-lg border border-border bg-card/55 p-4"><p className="flex items-center gap-2 text-sm font-medium"><Bot className="size-3.5 text-primary" />{name}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{note}</p></article>)}</div><div className="mt-4 rounded-lg border border-primary/20 bg-primary/[0.08] p-4"><p className="flex items-center gap-2 text-sm font-medium"><Sparkles className="size-4 text-primary" />Consensus</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Refactor authentication before implementing payments.</p></div></section>; }
