"use client";

import { BrainCircuit, CheckCircle2, GitBranch, History, Play, Radar, ShieldAlert, Sparkles, Target, TrendingUp } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { useKeyboardShortcuts } from "@/hooks/use-keyboard-shortcuts";
import { cn } from "@/lib/utils";

type Agent = { name: string; role: string; Icon: LucideIcon; tone: string; reasoning: string };
const agents: Agent[] = [
  { name: "Nova", role: "Product strategy", Icon: Sparkles, tone: "border-primary/30 bg-primary/[0.06] text-primary", reasoning: "The onboarding flow is the highest-leverage path to a clearer activation moment. Ship a narrow version, then learn from the first cohort." },
  { name: "Atlas", role: "Engineering", Icon: BrainCircuit, tone: "border-violet-400/30 bg-violet-400/[0.06] text-violet-300", reasoning: "The current scope is shippable this week if authentication coverage is completed first. Avoid adding new branches to the flow." },
  { name: "Echo", role: "Memory & history", Icon: History, tone: "border-emerald-400/30 bg-emerald-400/[0.06] text-emerald-300", reasoning: "The last two launches slowed when testing moved late. Your strongest releases began with a specific customer signal." },
  { name: "Pulse", role: "Market signals", Icon: Radar, tone: "border-amber-400/30 bg-amber-400/[0.06] text-amber-200", reasoning: "Early feedback consistently asks for confidence at the start. A guided first session directly addresses that signal." },
];
const graph = [
  { id: "launch", label: "Launch onboarding", detail: "The decision: ship a focused onboarding path for the first customer cohort.", x: "8%", y: "45%" },
  { id: "feedback", label: "User feedback", detail: "First-session feedback confirms where clarity is earned and where the flow loses momentum.", x: "29%", y: "19%" },
  { id: "retention", label: "Retention improved", detail: "A clearer start increases the number of founders returning after their first session.", x: "52%", y: "52%" },
  { id: "pricing", label: "Pricing changed", detail: "A stronger activation moment makes the product’s value easier to price with conviction.", x: "72%", y: "22%" },
  { id: "revenue", label: "Revenue increased", detail: "More retained, activated founders create sustainable revenue movement.", x: "81%", y: "66%" },
];
const lessons = [
  ["Repeated pattern", "Testing is most often delayed in the final 20% before launch."],
  ["Strongest signal", "Every successful feature began with a customer interview."],
  ["Momentum", "You move faster when one decision has a named owner and a short horizon."],
];

export function StrategyRoom() {
  const [question, setQuestion] = useState("Should I launch onboarding this week?");
  const [running, setRunning] = useState(false);
  const [arrived, setArrived] = useState(0);
  const [selected, setSelected] = useState(graph[0]);
  const begin = () => { setArrived(0); setRunning(true); };
  useKeyboardShortcuts([{ key: "Enter", meta: true, handler: begin }]);
  useEffect(() => {
    if (!running) return;
    const timers = agents.map((_, index) => window.setTimeout(() => setArrived(index + 1), 700 + index * 760));
    return () => timers.forEach(window.clearTimeout);
  }, [running]);
  const complete = running && arrived === agents.length;
  return <div className="mx-auto w-full max-w-7xl px-5 py-9 sm:px-8 lg:px-10 lg:py-12">
    <section className="animate-rise border-b border-border/70 pb-9"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-primary">Founder Intelligence Engine</p><div className="mt-3 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-4xl font-semibold tracking-[-0.035em] sm:text-5xl">A room for the decisions<br className="hidden sm:block" /> that change the company.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-muted-foreground">Independent perspectives, one considered recommendation. No chat stream—just the signal behind your next move.</p></div><div className="flex items-center gap-2 text-sm text-muted-foreground"><span className="size-2 rounded-full bg-primary shadow-[0_0_16px_hsl(var(--primary))]" />{running ? `${arrived} of ${agents.length} perspectives received` : "Council available"}</div></div></section>
    <section className="mt-8 animate-rise animation-delay-1" aria-labelledby="question-title"><div className="rounded-xl border border-border bg-card/60 p-5 sm:p-6"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-primary"><Target className="size-4" />Founder question</div><label id="question-title" className="sr-only">Question for the strategy room</label><textarea value={question} onChange={(event) => setQuestion(event.target.value)} rows={2} className="mt-4 w-full resize-none bg-transparent text-xl font-medium tracking-tight outline-none placeholder:text-muted-foreground sm:text-2xl" aria-label="Question for the strategy room" /><div className="mt-4 flex flex-col gap-3 border-t border-border pt-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-muted-foreground">Your reasoning, context, and outcome will be added to the timeline.</p><Button onClick={begin} disabled={!question.trim()}>{running ? "Run council again" : "Ask the council"}<Play className="ml-2 size-4" /></Button></div></div></section>
    <div className="mt-8 grid gap-8 xl:grid-cols-[minmax(0,1.52fr)_minmax(320px,0.8fr)]"><div className="space-y-8"><section className="animate-rise animation-delay-2" aria-labelledby="perspectives-title"><SectionTitle id="perspectives-title" eyebrow="Independent perspectives" title={running ? "The room is thinking." : "Invite the room to think."} /><div className="mt-5 grid gap-3 sm:grid-cols-2">{agents.map((agent, index) => <AgentPanel key={agent.name} agent={agent} state={arrived > index ? "arrived" : running ? "thinking" : "waiting"} />)}</div></section>
    {complete && <section className="animate-rise" aria-labelledby="consensus-title"><div className="overflow-hidden rounded-xl border border-primary/25 bg-gradient-to-br from-primary/[0.12] via-card to-card p-6 sm:p-7"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-primary"><Sparkles className="size-4" />Consensus</p><h2 id="consensus-title" className="mt-3 text-2xl font-semibold tracking-tight">Launch this week—with a disciplined scope.</h2><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">We collaborated and recommend releasing onboarding to a small cohort after the authentication test path is complete. Keep the first session narrow enough to learn before broadening the experience.</p><div className="mt-7 grid gap-5 border-t border-primary/15 pt-6 sm:grid-cols-3"><Consensus label="Areas of agreement" text="Activation clarity matters more than feature breadth." Icon={CheckCircle2} /><Consensus label="Potential risks" text="Testing too late repeats a known launch pattern." Icon={ShieldAlert} /><Consensus label="Trade-off" text="A smaller cohort slows reach but protects learning quality." Icon={TrendingUp} /></div><div className="mt-6 flex flex-col gap-4 rounded-lg border border-border/80 bg-background/45 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Final action plan</p><p className="mt-1 text-sm font-medium">Test auth today · ship to 10 founders Thursday · review signals Friday</p></div><div className="shrink-0 text-right"><p className="text-xs text-muted-foreground">Confidence</p><p className="text-xl font-semibold text-primary">86%</p></div></div></div></section>}</div>
    <aside className="space-y-8"><section className="animate-rise animation-delay-2 rounded-xl border border-border bg-card/55 p-5" aria-labelledby="memory-title"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Living memory</p><h2 id="memory-title" className="mt-2 text-xl font-semibold tracking-tight">This decision has a history.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{complete ? "Question, reasoning, recommendation, and outcome are now recorded in your timeline." : "When the council concludes, the full reasoning trail becomes part of your company memory."}</p><div className="mt-5 border-l border-primary/50 pl-4 text-sm"><p className="font-medium">{complete ? "Decision recorded now" : "Previous decision · Monday"}</p><p className="mt-1 text-muted-foreground">Onboarding scope narrowed after customer interview review.</p></div></section><FounderDna /></aside></div>
    <div className="mt-10 grid gap-8 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,0.85fr)]"><section className="animate-rise animation-delay-3" aria-labelledby="graph-title"><SectionTitle id="graph-title" eyebrow="Decision graph" title="See what each decision set in motion." /><div className="relative mt-5 min-h-[340px] overflow-hidden rounded-xl border border-border bg-card/45 p-5"><svg className="absolute inset-0 size-full text-border" aria-hidden="true" viewBox="0 0 800 340" preserveAspectRatio="none"><path d="M110 173 L270 70 L450 180 L610 80 L680 225" fill="none" stroke="currentColor" strokeWidth="1.25" strokeDasharray="5 5" /></svg>{graph.map((node) => <button key={node.id} onClick={() => setSelected(node)} style={{ left: node.x, top: node.y }} className={cn("absolute -translate-x-1/2 -translate-y-1/2 rounded-full border px-3 py-2 text-xs font-medium shadow-lg transition-all duration-300 hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring", selected.id === node.id ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card text-foreground hover:border-primary/50")}>{node.label}</button>)}<div className="absolute bottom-5 left-5 right-5 rounded-lg border border-border bg-background/80 p-4 backdrop-blur-sm"><p className="flex items-center gap-2 text-sm font-medium"><GitBranch className="size-4 text-primary" />{selected.label}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{selected.detail}</p></div></div></section><section className="animate-rise animation-delay-3" aria-labelledby="learning-title"><SectionTitle id="learning-title" eyebrow="Learning engine" title="What the work is teaching you." /><div className="mt-5 space-y-3">{lessons.map(([label, detail]) => <article key={label} className="rounded-xl border border-border bg-card/55 p-4"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">{label}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{detail}</p></article>)}</div></section></div>
  </div>;
}
function SectionTitle({ id, eyebrow, title }: { id: string; eyebrow: string; title: string }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">{eyebrow}</p><h2 id={id} className="mt-2 text-xl font-semibold tracking-tight sm:text-2xl">{title}</h2></div>; }
function AgentPanel({ agent, state }: { agent: Agent; state: "waiting" | "thinking" | "arrived" }) { const { Icon } = agent; return <article className={cn("min-h-48 rounded-xl border p-5 transition-all duration-500", state === "arrived" ? agent.tone : "border-border bg-card/55")}><div className="flex items-start justify-between"><div className="flex items-center gap-3"><span className={cn("flex size-9 items-center justify-center rounded-lg border", state === "arrived" ? agent.tone : "border-border bg-secondary text-muted-foreground")}><Icon className="size-4" /></span><div><h3 className="font-medium">{agent.name}</h3><p className="text-xs text-muted-foreground">{agent.role}</p></div></div>{state === "thinking" && <span className="flex gap-1" aria-label={`${agent.name} is thinking`}><i className="size-1.5 animate-pulse rounded-full bg-primary" /><i className="size-1.5 animate-pulse rounded-full bg-primary [animation-delay:150ms]" /><i className="size-1.5 animate-pulse rounded-full bg-primary [animation-delay:300ms]" /></span>}{state === "arrived" && <CheckCircle2 className="size-4" />}</div><div className="mt-7">{state === "arrived" ? <p className="text-sm leading-6 text-muted-foreground">{agent.reasoning}</p> : <p className="text-sm text-muted-foreground">{state === "thinking" ? `${agent.name} is thinking independently…` : "Waiting for the council to begin."}</p>}</div></article>; }
function Consensus({ label, text, Icon }: { label: string; text: string; Icon: LucideIcon }) { return <div><p className="flex items-center gap-2 text-sm font-medium"><Icon className="size-4 text-primary" />{label}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>; }
function FounderDna() { const traits = [["Decision speed", "Deliberate", 72], ["Risk tolerance", "Measured", 64], ["Shipping consistency", "Strong", 83], ["Focus score", "Protected", 78], ["Learning velocity", "Accelerating", 88], ["Energy trend", "Rising", 70]]; return <section className="animate-rise animation-delay-3" aria-labelledby="dna-title"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Founder DNA</p><h2 id="dna-title" className="mt-2 text-xl font-semibold tracking-tight">A profile in motion.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Not a scorecard—an evolving picture of how you build.</p><div className="mt-5 space-y-4">{traits.map(([name, descriptor, value]) => <div key={name as string}><div className="flex justify-between text-sm"><span>{name}</span><span className="text-muted-foreground">{descriptor}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary/80" style={{ width: `${value}%` }} /></div></div>)}</div></section>; }
