"use client";

import { AnimatePresence, motion } from "framer-motion";
import { Activity, Bot, CheckCircle2, FilePlus2, GitBranch, Grip, Layers3, Search, ShieldCheck, Sparkles, X, Zap } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { collaborators, knowledgeNodes, searchRecords, type KnowledgeNode } from "@/lib/collaboration";
import { currentContext } from "@/lib/founder-memory";
import { useKeyboardShortcuts } from "@/hooks/use-keyboard-shortcuts";
import { cn } from "@/lib/utils";

const health: [string, string, number, LucideIcon][] = [["Product", "Activation path has a focused cohort plan.", 82, Sparkles], ["Engineering", "Auth validation is the remaining launch gate.", 74, GitBranch], ["Growth", "Customer signal is strong but limited to the first cohort.", 71, Activity], ["Design", "First session is coherent and intentionally constrained.", 86, Layers3], ["Testing", "Coverage needs to move earlier in the release cycle.", 58, CheckCircle2], ["Documentation", "Decision records are current; onboarding notes need a final pass.", 76, FilePlus2], ["Deployment", "Main branch is deployment-ready.", 91, Zap], ["Security", "Environment boundaries are in place; auth flow needs end-to-end testing.", 79, ShieldCheck]];
const insights = [["Project risk", "Medium", "Testing remains the only unprotected launch constraint."], ["Launch readiness", "78%", "A ten-founder cohort can launch once authentication validation closes."], ["Engineering velocity", "Rising", "42 commits this week, with the dashboard and intelligence surfaces moving together."], ["Founder burnout risk", "Low", "Focus is protected, but decision load increased over the past three days."], ["Customer feedback", "Clear", "Founders want confidence in the first session—not more features."], ["Upcoming bottleneck", "Auth", "Payment work should wait until authentication ownership is consolidated."]];
const taskSeeds = [["Validate the complete authentication flow", "Atlas review · GitHub b5ac90d", "High"], ["Run five first-session interviews", "Pulse feedback · Customer interview timeline", "High"], ["Record onboarding cohort decision", "Nova recommendation · Voice Workspace", "Medium"]] as const;

export function CollaborationWorkspace() {
  const [searchOpen, setSearchOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [graphOpen, setGraphOpen] = useState(false);
  const [selectedNode, setSelectedNode] = useState<KnowledgeNode>(knowledgeNodes[0]);
  const [taskOpen, setTaskOpen] = useState(false);
  const [tasks, setTasks] = useState([...taskSeeds]);
  const [typing, setTyping] = useState(true);
  const [cursorOffset, setCursorOffset] = useState(0);
  const results = useMemo(() => { const term = query.toLowerCase().trim(); if (!term) return searchRecords; const semantic = term.includes("last tuesday") ? ["last tuesday"] : term.includes("supabase") ? ["supabase"] : term.includes("nova") ? ["nova"] : term.includes("pricing") ? ["pricing"] : term.split(/\s+/); return searchRecords.filter((record) => semantic.some((word) => `${record.title} ${record.detail} ${record.tags.join(" ")}`.toLowerCase().includes(word))); }, [query]);
  useEffect(() => { const timer = window.setInterval(() => setTyping((value) => !value), 2400); const cursor = window.setInterval(() => setCursorOffset((value) => (value + 1) % 3), 1800); return () => { window.clearInterval(timer); window.clearInterval(cursor); }; }, []);
  useKeyboardShortcuts([{ key: "f", meta: true, shift: true, handler: () => setSearchOpen(true) }, { key: "l", meta: true, shift: true, handler: () => setGraphOpen(true) }, { key: "t", meta: true, shift: true, handler: () => setTaskOpen(true) }]);
  const addTask = (task: (typeof taskSeeds)[number]) => { setTasks((existing) => existing.some(([title]) => title === task[0]) ? existing : [...existing, task]); setTaskOpen(false); };
  return <div className="mx-auto w-full max-w-7xl px-5 py-9 sm:px-8 lg:px-10 lg:py-12">
    <section className="animate-rise border-b border-border/70 pb-9"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-primary">Real-time collaboration</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.035em] sm:text-5xl">The project is alive<br />while you build it.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-muted-foreground">People, decisions, commits, and AI memory stay connected in one calm operating surface.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setSearchOpen(true)}><Search className="mr-2 size-4" />Search</Button><Button variant="outline" onClick={() => setGraphOpen(true)}><GitBranch className="mr-2 size-4" />Knowledge graph</Button><Button onClick={() => setTaskOpen(true)}><FilePlus2 className="mr-2 size-4" />Create task</Button></div></div></section>
    <div className="mt-8 grid gap-8 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,0.82fr)]"><div className="space-y-8"><section className="animate-rise animation-delay-1 rounded-xl border border-border bg-card/55 p-5 sm:p-6" aria-labelledby="project-title"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Live project</p><h2 id="project-title" className="mt-2 text-xl font-semibold tracking-tight">{currentContext.project}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{currentContext.focus} · {currentContext.repository} / {currentContext.branch}</p></div><div className="flex items-center gap-2"><div className="flex -space-x-2">{collaborators.map((person) => <span key={person.name} title={`${person.name} · ${person.role}`} className={cn("relative flex size-8 items-center justify-center rounded-full border-2 border-card text-[10px] font-semibold text-background", person.color)}>{person.initials}<i className="absolute -bottom-0.5 -right-0.5 size-2 rounded-full border border-card bg-emerald-300" /></span>)}</div><span className="text-xs text-muted-foreground">{collaborators.length} active</span></div></div><div className="relative mt-6 min-h-48 overflow-hidden rounded-lg border border-border bg-background/45 p-5"><div className="flex items-center gap-2 text-sm"><Grip className="size-4 text-primary" />Onboarding cohort decision</div><p className="mt-3 max-w-md text-sm leading-6 text-muted-foreground">Ship to ten founders after the authentication flow is validated. Keep the release intentionally narrow and learn from the first session.</p>{collaborators.map((person, index) => <motion.div key={person.name} animate={{ x: index === cursorOffset ? 12 : 0, y: index === cursorOffset ? -4 : 0 }} className="absolute" style={{ left: `${18 + index * 29}%`, top: `${55 + index * 11}%` }}><span className={cn("flex items-center gap-1 rounded bg-card px-2 py-1 text-[10px] shadow-lg", person.color === "bg-primary" ? "text-primary" : person.color === "bg-violet-400" ? "text-violet-300" : "text-emerald-300")}><span className={cn("size-1.5 rounded-full", person.color)} />{person.name.split(" ")[0]}</span></motion.div>)}</div><div className="mt-4 flex flex-wrap items-center gap-4 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><span className="size-1.5 rounded-full bg-emerald-300" />Synced just now</span><span className="flex items-center gap-1.5"><Bot className="size-3.5 text-primary" />Nova and Atlas are watching this decision</span>{typing && <span className="flex items-center gap-1.5"><span className="flex gap-0.5"><i className="size-1 rounded-full bg-primary" /><i className="size-1 rounded-full bg-primary" /><i className="size-1 rounded-full bg-primary" /></span>Maya is typing a note</span>}</div></section>
    <section className="animate-rise animation-delay-2" aria-labelledby="tasks-title"><Header eyebrow="Smart tasks" id="tasks-title" title="Work generated from real evidence." /><div className="mt-5 space-y-3">{tasks.map(([title, origin, priority]) => <article key={title} className="flex flex-col gap-3 rounded-xl border border-border bg-card/55 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-muted-foreground">Linked to {origin}</p></div><span className={cn("rounded-full border px-2.5 py-1 text-xs", priority === "High" ? "border-amber-300/25 text-amber-200" : "border-primary/25 text-primary")}>{priority}</span></article>)}</div></section></div>
    <aside className="space-y-8"><section className="animate-rise animation-delay-2" aria-labelledby="insights-title"><Header eyebrow="AI project insights" id="insights-title" title="The system sees around corners." /><div className="mt-5 space-y-3">{insights.map(([title, signal, detail]) => <article key={title} className="rounded-lg border border-border bg-card/55 p-4"><div className="flex items-center justify-between"><p className="text-sm font-medium">{title}</p><span className="text-xs text-primary">{signal}</span></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{detail}</p></article>)}</div></section></aside></div>
    <section className="mt-10 animate-rise animation-delay-3" aria-labelledby="health-title"><Header eyebrow="Project health" id="health-title" title="A quiet read on what needs care." /><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{health.map(([title, observation, score, Icon]) => <article key={title} className="rounded-xl border border-border bg-card/55 p-5 transition-all duration-300 hover:-translate-y-0.5 hover:border-primary/30"><div className="flex items-center justify-between"><p className="font-medium">{title}</p><Icon className="size-4 text-primary" /></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-secondary"><motion.div initial={{ width: 0 }} whileInView={{ width: `${score}%` }} viewport={{ once: true }} className="h-full rounded-full bg-primary/80" /></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{observation}</p></article>)}</div></section>
    <section className="mt-10 flex flex-wrap gap-x-6 gap-y-3 border-t border-border/70 pt-6 text-xs text-muted-foreground"><span><kbd className="mr-2 rounded border border-border bg-card px-1.5 py-1 font-sans text-[10px] text-foreground">Ctrl ⇧ F</kbd>Universal search</span><span><kbd className="mr-2 rounded border border-border bg-card px-1.5 py-1 font-sans text-[10px] text-foreground">Ctrl ⇧ L</kbd>Knowledge graph</span><span><kbd className="mr-2 rounded border border-border bg-card px-1.5 py-1 font-sans text-[10px] text-foreground">Ctrl ⇧ T</kbd>Create task</span></section>
    <AnimatePresence>{searchOpen && <SearchOverlay query={query} setQuery={setQuery} results={results} close={() => setSearchOpen(false)} />}{graphOpen && <GraphOverlay selected={selectedNode} select={setSelectedNode} close={() => setGraphOpen(false)} />}{taskOpen && <TaskOverlay add={addTask} close={() => setTaskOpen(false)} />}</AnimatePresence>
  </div>;
}
function Header({ eyebrow, id, title }: { eyebrow: string; id: string; title: string }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">{eyebrow}</p><h2 id={id} className="mt-2 text-xl font-semibold tracking-tight sm:text-2xl">{title}</h2></div>; }
function Overlay({ children, close, label }: { children: React.ReactNode; close: () => void; label: string }) { return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-40 flex items-start justify-center bg-background/80 p-4 pt-[10vh] backdrop-blur-sm" role="dialog" aria-modal="true" aria-label={label} onClick={close}><motion.div initial={{ y: 12, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: 12, opacity: 0 }} onClick={(event) => event.stopPropagation()} className="max-h-[78vh] w-full max-w-4xl overflow-auto rounded-xl border border-border bg-card p-5 shadow-2xl">{children}</motion.div></motion.div>; }
function SearchOverlay({ query, setQuery, results, close }: { query: string; setQuery: (value: string) => void; results: typeof searchRecords; close: () => void }) { return <Overlay close={close} label="Universal search"><div className="flex items-center gap-3 border-b border-border pb-4"><Search className="size-5 text-primary" /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent text-lg outline-none placeholder:text-muted-foreground" placeholder="Search decisions, commits, conversations, and lessons…" /><button onClick={close} aria-label="Close search"><X className="size-4 text-muted-foreground" /></button></div><p className="mt-4 text-xs font-semibold uppercase tracking-[0.18em] text-primary">Universal results</p><div className="mt-3 space-y-2">{results.map((result) => <button key={result.title} onClick={close} className="w-full rounded-lg border border-border p-4 text-left transition-colors hover:border-primary/35 hover:bg-accent/40"><div className="flex justify-between gap-4"><p className="font-medium">{result.title}</p><span className="text-xs text-primary">{result.kind}</span></div><p className="mt-1 text-sm leading-6 text-muted-foreground">{result.detail}</p></button>)}{results.length === 0 && <p className="py-10 text-center text-sm text-muted-foreground">No signal found yet. Try “onboarding”, “Supabase”, or “last Tuesday”.</p>}</div></Overlay>; }
function GraphOverlay({ selected, select, close }: { selected: KnowledgeNode; select: (node: KnowledgeNode) => void; close: () => void }) { return <Overlay close={close} label="AI knowledge graph"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">AI knowledge graph</p><h2 className="mt-1 text-xl font-semibold">Everything is connected.</h2></div><button onClick={close} aria-label="Close graph"><X className="size-4 text-muted-foreground" /></button></div><div className="relative mt-5 min-h-[470px] overflow-hidden rounded-lg border border-border bg-background/45"><svg className="absolute inset-0 size-full text-border" viewBox="0 0 1000 470" preserveAspectRatio="none"><path d="M150 225 L340 100 L500 225 L660 90 L780 235 M340 100 L320 360 L500 225 L570 360" fill="none" stroke="currentColor" strokeWidth="1.4" strokeDasharray="5 5" /></svg>{knowledgeNodes.map((node) => <motion.button drag key={node.id} initial={{ opacity: 0, scale: 0.7 }} animate={{ opacity: 1, scale: 1 }} onClick={() => select(node)} style={{ left: node.x, top: node.y }} className={cn("absolute -translate-x-1/2 -translate-y-1/2 rounded-full border px-3 py-2 text-xs font-medium shadow-lg", selected.id === node.id ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card text-foreground")}>{node.type} · {node.label}</motion.button>)}<div className="absolute bottom-5 left-5 right-5 rounded-lg border border-border bg-card/95 p-4 backdrop-blur-sm"><p className="text-sm font-medium">{selected.type} · {selected.label}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{selected.detail}</p></div></div><p className="mt-3 text-xs text-muted-foreground">Drag nodes to explore the relationship space. Select a node to surface its linked history.</p></Overlay>; }
function TaskOverlay({ add, close }: { add: (task: (typeof taskSeeds)[number]) => void; close: () => void }) { return <Overlay close={close} label="Create smart task"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Smart task generation</p><h2 className="mt-1 text-xl font-semibold">Tasks with their evidence attached.</h2></div><button onClick={close} aria-label="Close task creation"><X className="size-4 text-muted-foreground" /></button></div><div className="mt-5 space-y-3">{taskSeeds.map((task) => <article key={task[0]} className="flex flex-col gap-3 rounded-lg border border-border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium">{task[0]}</p><p className="mt-1 text-sm text-muted-foreground">Origin: {task[1]}</p></div><Button size="sm" onClick={() => add(task)}>Add task</Button></article>)}</div></Overlay>; }
