"use client";

import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, BrainCircuit, CheckCircle2, GitBranch, Mic, PlayCircle, Sparkles } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";

const steps = [{ title: "Your timeline has a memory.", detail: "Capture decisions, customer signals, commits, and lessons in one connected history.", Icon: Sparkles }, { title: "Invite the right perspectives.", detail: "Nova, Atlas, Echo, Pulse, and Compass reason independently before the system recommends a move.", Icon: BrainCircuit }, { title: "Replay how the work happened.", detail: "Follow a decision from idea to feedback, implementation, launch, and learning.", Icon: PlayCircle }, { title: "Work by voice when the moment matters.", detail: "Voice Workspace keeps your project, repository, decisions, and history in context.", Icon: Mic }, { title: "See the system behind the work.", detail: "Knowledge Graph connects product, code, customers, and the lessons that compound.", Icon: GitBranch }];

export function Onboarding({ open, close }: { open: boolean; close: () => void }) { const [step, setStep] = useState(0); const current = steps[step]; const finish = () => { localStorage.setItem("logfound-onboarded", "true"); close(); }; return <AnimatePresence>{open && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 flex items-center justify-center bg-background/85 p-4 backdrop-blur-xl" role="dialog" aria-modal="true" aria-label="Logfound introduction"><motion.section initial={{ opacity: 0, y: 16, scale: 0.98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 16 }} className="w-full max-w-xl overflow-hidden rounded-2xl border border-primary/20 bg-card shadow-2xl"><div className="h-1 bg-secondary"><motion.div animate={{ width: `${((step + 1) / steps.length) * 100}%` }} className="h-full bg-primary" /></div><div className="p-7 sm:p-9"><div className="flex size-12 items-center justify-center rounded-xl border border-primary/25 bg-primary/[0.1] text-primary"><current.Icon className="size-6" /></div><p className="mt-8 text-xs font-semibold uppercase tracking-[0.22em] text-primary">Welcome to Logfound · {step + 1} of {steps.length}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">{current.title}</h2><p className="mt-4 max-w-md text-base leading-7 text-muted-foreground">{current.detail}</p><div className="mt-9 flex items-center justify-between"><button onClick={finish} className="text-sm text-muted-foreground hover:text-foreground">{step === steps.length - 1 ? "Finish" : "Skip introduction"}</button><Button onClick={() => step === steps.length - 1 ? finish() : setStep(step + 1)}>{step === steps.length - 1 ? <>Enter workspace <CheckCircle2 className="ml-2 size-4" /></> : <>Continue <ArrowRight className="ml-2 size-4" /></>}</Button></div></div></motion.section></motion.div>}</AnimatePresence>; }
