import { z } from "zod";
import { aiMemory, defaultWorkspaceContext, memoryRecord } from "@/lib/ai/memory";
import { getAiClient, toSafeAiError } from "@/lib/ai/client";
import { generateAgentContribution, generateConsensus, selectAgents, streamSingleAgent } from "@/lib/ai/router";
import type { AiOperation, AiStreamEvent, WorkspaceContext } from "@/lib/ai/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const requestSchema = z.object({ operation: z.enum(["ask", "collaborate", "summary", "weekly_review", "replay", "founder_dna"]), question: z.string().trim().min(1).max(4_000), agent: z.enum(["nova", "atlas", "echo", "pulse", "compass"]).optional(), context: z.object({ project: z.string().max(200).optional(), repository: z.string().max(200).optional(), branch: z.string().max(100).optional(), timeline: z.array(z.string().max(800)).max(20).optional(), recentCommits: z.array(z.string().max(800)).max(20).optional(), founderHistory: z.array(z.string().max(800)).max(20).optional(), previousDecisions: z.array(z.string().max(800)).max(20).optional(), relevantMemories: z.array(z.string().max(800)).max(20).optional() }).optional(), remember: z.boolean().optional().default(true), stream: z.boolean().optional().default(true) });

function clean(value: string) { return value.replace(/[\u0000-\u001F\u007F]/g, " ").replace(/\s+/g, " ").trim(); }
function mergeContext(base: WorkspaceContext, supplied?: Partial<WorkspaceContext>): WorkspaceContext { if (!supplied) return base; return { project: supplied.project ? clean(supplied.project) : base.project, repository: supplied.repository ? clean(supplied.repository) : base.repository, branch: supplied.branch ? clean(supplied.branch) : base.branch, timeline: (supplied.timeline || base.timeline).map(clean), recentCommits: (supplied.recentCommits || base.recentCommits).map(clean), founderHistory: (supplied.founderHistory || base.founderHistory).map(clean), previousDecisions: (supplied.previousDecisions || base.previousDecisions).map(clean), relevantMemories: (supplied.relevantMemories || base.relevantMemories).map(clean) }; }
function send(controller: ReadableStreamDefaultController<Uint8Array>, event: AiStreamEvent) { controller.enqueue(new TextEncoder().encode(`event: ${event.type}\ndata: ${JSON.stringify(event)}\n\n`)); }
function operationQuestion(operation: AiOperation, question: string) { const prefixes: Record<Exclude<AiOperation, "ask" | "collaborate">, string> = { summary: "Create a concise founder workspace summary for:", weekly_review: "Create a weekly founder review for:", replay: "Explain this decision replay and its lessons:", founder_dna: "Assess the founder operating profile from this context:" }; return operation === "ask" || operation === "collaborate" ? question : `${prefixes[operation]} ${question}`; }

export async function POST(request: Request) {
  let payload: z.infer<typeof requestSchema>;
  try { payload = requestSchema.parse(await request.json()); } catch { return Response.json({ error: { code: "invalid_request", message: "Provide a valid AI operation and a question under 4,000 characters." } }, { status: 400 }); }
  const memories = await aiMemory.recent(payload.context?.project || "Logfound activation");
  const context = mergeContext(defaultWorkspaceContext(memories), payload.context);
  const question = clean(payload.question);
  if (!payload.stream) {
    try { const client = getAiClient(); const agents = selectAgents(question, payload.operation, payload.agent); const contributions = await Promise.all(agents.map((agent) => generateAgentContribution(agent, operationQuestion(payload.operation, question), context))); const output = contributions.length > 1 ? await generateConsensus(question, context, contributions) : contributions[0].content; return Response.json({ provider: client.name, model: client.model, agents, contributions, output }); } catch (error) { const safe = toSafeAiError(error); return Response.json({ error: safe }, { status: safe.status }); }
  }
  const stream = new ReadableStream<Uint8Array>({ async start(controller) { let output = ""; try { const client = getAiClient(); const agents = selectAgents(question, payload.operation, payload.agent); send(controller, { type: "meta", provider: client.name, model: client.model, operation: payload.operation, agents }); send(controller, { type: "status", phase: "thinking", message: "Understanding the founder request…" }); if (agents.length > 1) { const contributions = []; for (const agent of agents) { send(controller, { type: "status", phase: "analyzing", message: `${agent[0].toUpperCase() + agent.slice(1)} is reviewing relevant context…` }); const contribution = await generateAgentContribution(agent, operationQuestion(payload.operation, question), context); contributions.push(contribution); send(controller, { type: "contribution", contribution }); } send(controller, { type: "status", phase: "collaborating", message: "Combining specialist reasoning…" }); output = await generateConsensus(question, context, contributions); send(controller, { type: "status", phase: "generating", message: "Generating the shared recommendation…" }); send(controller, { type: "delta", text: output }); } else { send(controller, { type: "status", phase: "searching", message: `${agents[0][0].toUpperCase() + agents[0].slice(1)} is reviewing relevant context…` }); send(controller, { type: "status", phase: "generating", message: "Generating a focused recommendation…" }); for await (const delta of streamSingleAgent(agents[0], operationQuestion(payload.operation, question), context)) { output += delta; send(controller, { type: "delta", text: delta }); } } const memory = payload.remember ? await aiMemory.remember(memoryRecord(question, payload.operation, context, agents, output.slice(0, 500))) : undefined; send(controller, { type: "complete", memoryId: memory?.id }); } catch (error) { const safe = toSafeAiError(error); console.error("[ai] request failed", { code: safe.code, operation: payload.operation }); send(controller, { type: "error", code: safe.code, message: safe.message }); } finally { controller.close(); } } });
  return new Response(stream, { headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-cache, no-transform", Connection: "keep-alive", "X-Accel-Buffering": "no" } });
}
